<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="./images/camagru.png" type="image/x-icon">
    <link rel="stylesheet" href="home.css">
    <link rel="stylesheet" href="filters.css">

    <title>Document</title>
</head>
<body>
    <div class="wrapper">
        <header>
            <div class="ico">

            </div>
        </header>
        <aside> 
            <div class="column">
                <script src="video.js"></script>
                <div class="left">
                    <div class="vid">
                        <div id="overlay">
                                <img ondragstart="return false" id="drag-img" />
                        </div>
                        <canvas  id="myCanvas"></canvas>
                        <script src="./overlay.js"></script>
                        <!-- <video id="video" autoplay></video> -->
                    </div>
                    <div class="buttons">
                        <button class="cam" id="c1" title="start webcam"></button>
                        <button class="cam" id="c2" title="Snapshort"></button>
                        <button class="cam" id="c3" title="Camcorder"></button>
                    </div>
                </div>
                <div class="preview">
                    <div id="stickers">
                    <?php
                        $files = glob("filters/*.*");
                        for ($i=0; $i<count($files); $i++) {
                            $image = $files[$i];
                            echo '<img id=ima"'.$i.'" onclick="addSticker(this)" class="mySlides" src="'.$image .'" alt="Random image" style="width:20%;height:30%;background-color:#'. str_pad(dechex(rand(0x000000, 0xFFFFFF)), 6, 0, STR_PAD_LEFT).'"/>';
                        }
                        ?>
                    </div>
                    <canvas  id="myCanvas2"></canvas>
                    <div class="buttons">
                        <button class="preview_button" id="save">save</button>
                        <a id="down" href="#"><button class="preview_button" id="download">download</button></a>
                    </div>
                </div>
            </div>
            <div id="scoop">

            </div> 
        </aside>


        <article>
            <div class="wrapper-content">
                <form id="form">
                    <label>Blur:</label><br>
                    <input type="range" id="blur" value="0" min="0" max="4" step="0.01"/><br>
                    <label>Brightness:</label><br>
                    <input type="range" id="brightness" value="1.2" min="1" max="2" step="0.01"/><br>
                    <label>Saturate:</label><br>
                    <input type="range" id="saturate" value="100" min="0" max="200" /><br>
                    <label>Hue:</label><br>
                    <input type="range" id="hue-rotate" value="0" min="0" max="360" /><br>
                    <label>Contrast:</label><br>
                    <input type="range" id="contrast" value="100" min="0" max="200" /><br>
                    <label>Invert:</label><br>
                    <input type="range" id="invert" value="0" min="0" max="100" /><br>
                    <label>Grayscale:</label><br>
                    <input type="range" id="grayscale" value="0" min="0" max="100" /><br>
                    <label>Sepia:</label><br>
                    <input type="range" id="sepia" value="0" min="0" max="100" /><br>
                       
                    <div class="buttons">
                        <button class="filter_buttons" id="gallery">GALLERY</button>
                        <button class="filter_buttons" onclick="reset(); myFunc();">RESET</button>
                    </div>
                </form><br>
            </div>

            <form method="POST" action="upload.php" enctype="multipart/form-data">
                <input type="hidden" name="size" value="1000000">
                <div>
                  <input type="file" name="image">
                    <button type="submit" name="upload">POST</button>
                </div>
            </form>
            <?php
                while ($row = $re->fetch(PDO::FETCH_ASSOC)) {
                echo "<div id='img_div'>";
                  echo "<img src='uploads/".$row['pics']."' style='width:300px;height:200px;' >";
            echo "</div>";
        }
        print_r($_SESSION);
        ?>
        </article>

        <footer>Footer</footer>
        
    </div>
</body>
</html>