<?php
/*
 *
 *    File created by Roger Ndaba
 *    Project: camagru
 *    File: home.phtml
 *
 */
    include('connect.php');
    $conn = conOpen();
    $re = $conn->query( "SELECT * FROM `images`");
    session_start();
 ?>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="./images/camagru.png" type="image/x-icon">
    <link rel="stylesheet" href="home.css">
    <link rel="stylesheet" href="filters.css">

    <title>Document</title>
</head>
<body>
    <div class="wrapper">
        <header>
            <div class="ico">

            </div>
        </header>


        <aside> 
            <div class="row">
                <div class="scoop">
                    <script src="video.js"></script>
                    <div class="column left"> 
                        <div class="vid"><video id="video" autoplay><img src="./images/icon.png"></video></div>
                        <div class="buttons">
                            <button id="c1"></button>
                            <button id="c2"></button>
                            <button id="c3"></button>
                        </div>
                    </div>
                    <div id="preview" class="preview">
                            <canvas  id="myCanvas"></canvas>

                    </div>
                    </div>
                    <div id="saved_images" class="right">
                    </div>
               
            </div>
        </aside>


        <article>
            <div class="wrapper-content">
                <form id="form">
                    <label>Blur:</label><br>
                    <input type="range" id="blur" value="0" min="0" max="4" step="0.01" oninput="myFunc()"/><br>
                    <label>Brightness:</label><br>
                    <input type="range" id="brightness" value="1" min=".5" max="4" step="0.01" oninput="myFunc()"/><br>
                    <label>Saturate:</label><br>
                    <input type="range" id="saturate" value="100" min="0" max="200" oninput="myFunc(this)"/><br>
                    <label>Hue:</label><br>
                    <input type="range" id="hue-rotate" value="0" min="0" max="360" oninput="myFunc(this)"/><br>
                    <label>Contrast:</label><br>
                    <input type="range" id="contrast" value="100" min="0" max="200" oninput="myFunc(this)"/><br>
                    <label>Invert:</label><br>
                    <input type="range" id="invert" value="0" min="0" max="100" oninput="myFunc(this)"/><br>
                    <label>Grayscale:</label><br>
                    <input type="range" id="grayscale" value="0" min="0" max="100" oninput="myFunc(this)"/><br>
                    <label>Sepia:</label><br>
                    <input type="range" id="sepia" value="0" min="0" max="100" oninput="myFunc(this)"/><br>


                    <input type="button" onclick="reset(); myFunc();" value="reset">
                    <input id="save"  type="button" value="Save Image">
                    <a id="down" href="#"><input type="button" id="download" value="download"></a>
                </form>
            </div>

            <form method="POST" action="upload.php" enctype="multipart/form-data">
                <input type="hidden" name="size" value="1000000">
                <div>
                  <input type="file" name="image">
                    <button type="submit" name="upload">POST</button>
                </div>
            </form>
            <?php
                while ($row = $re->fetch(PDO::FETCH_ASSOC)) {
                echo "<div id='img_div'>";
                  echo "<img src='uploads/".$row['pics']."' style='width:300px;height:200px;' >";
            echo "</div>";
        }
        print_r($_SESSION);
        ?>
        </article>

        <footer>Footer</footer>
        
    </div>
</body>
</html>