<?php
/*
 *
 *    File created by Roger Ndaba
 *    Project: camagru
 *    File: login.phtml
 *
 */

    include("connect.php");

    // if (isset($_GET['ok']) && $_GET['ok'] == 1) {
    //     $conn = conOpen();

    //     $q = "UPDATE "
    //     header("Location: home.html");
    //     session_start();
    // }
?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="google-signin-client_id" content="YOUR_CLIENT_ID.apps.googleusercontent.com">
        <link rel="stylesheet" href="login.css">
        <title>Document</title>
    </head>
    <body>
        
        <div class="login_class">
            <div class="login_container">
                    <form id='index' action='login.php' method='post' accept-charset='UTF-8' autocomplete="off">
                       <span class="error_msg">
                            <?php
                            $bg = #ffffff;
                            $msg = base64_decode($_GET['msg']);
                            if(isset($_GET['msg']))
                                echo $msg;
                            unset($_GET['msg']);
                            ?>
                       </span>
                       <input type='hidden' name='submitted' id='submitted' value='1' style="background-color:<?php echo $bg?>"/>
                       <input type='text' name='login' id='login'  maxlength="500" placeholder="Username or Email"/><br>
                       <input type='password' name='passwd' id='passwd' maxlength="50" placeholder="Password"/><br>
                       <input type='submit' name='submit' value='Sign in'/>      
                    </form>
                    <a class="create_account" href="new_account.phtml" style="color:#579ff1">
                        Create Account
                    </a>
            </div>
        </div>
    </body>
</html>