/*
 *
 *    File created by Roger Ndaba
 *    Project: camagru
 *    File: new_account.phtml
 *
 */
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="./images/camagru.png" type="image/x-icon">
    <link rel="stylesheet" href="new_account.css">
    
    <title>new_account</title>
</head>
<body>
    <div class="info_box">
        <div class="info">
            <span class="error_msg">
                <?php
                    if(isset($_GET['msg'])) {
                        $msg = base64_decode($_GET['msg']);
                        echo $msg;
                        unset($_GET['msg']);
                    }
                ?>
            </span>
            <form id='new_account' action='new_account.php' method='post' accept-charset='UTF-8'>
                           
                <input type='hidden' name='submitted' id='submitted' value='1'/>
                <label for='name' >Name<span>*</span></label><br>
                <input type='text' name='name' id='name'  maxlength="50" pattern="[a-zA-Z0-9_]+$" title="Only letters, numbers and underscores"/><br>

                <label for='surname' >Surname<span>*</span></label>
                <input type='text' name='surname' id='surname' maxlength="50" pattern="[a-zA-Z0-9_]+$" title="Only letters, numbers and underscores"/><br>

                <label for='login' >Username<span>*</span></label><br>
                <input type='text' name='login' id='login'  maxlength="50" pattern="[a-zA-Z0-9_]+$" title="Only letters, numbers and underscores"/><br>

                <label for='passwd' >Password<span>*</span></label>
                <input type='password' name='passwd' id='passwd' maxlength="50" autocomplete="false" onkeyup="strength()">
                <script>
                
                var counter = 0;
                function strength() {
                var str = document.getElementById("strength");
                var string = document.getElementById("passwd").value;
                    if (/[a-z]/.test(string))
                        str.value++;
                    if (/[A-Z]/.test(string))
                        str.value = 2;
                    if (/[0-9]/.test(string))
                        str.value = 3;
                    if (/[!@#$&*]/.test(string))
                        str.value = 4;
                }
                
                </script>
                <meter max="4" id="strength"  value="0"></meter><br><br>

                <label for='email' >Email<span>*</span></label><br>
                <input type='text' name='email' id='email'  maxlength="50" /><br>

                <script src="https://www.google.com/recaptcha/api.js" async defer></script>
                <div class="g-recaptcha" data-sitekey="6LeaWnYUAAAAAFuFapEu-y1BjnRNHLpHXv4WJ8hV" data-theme="dark" data-size="normal"></div>

                <input type='submit' name='submit' value='CREATE'/>
            </form>
        </div>
    </div>
</body>
</html>