<?php
/*
 *
 *    File created by Roger Ndaba
 *    Project: camagru
 *    File: public.phtml
 *
 */
?>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="public.css">
    <title>Camagru Public</title>


</head>
<body>
    <div class="icon_wrapper">
        <div class="icon">
        <a href="index.html"><img src="./images/black_camagru.png" class="ims"></a>    
        </div>
    </div>
<div id="container">
    <nav>
        <ul>
            <li><a href="#">home</a>
                <ul>
                    <li><a href="login.phtml">LOGIN</a></li>
                    <li><a href="new_account.phtml">SIGN UP</a></li>
                </ul>
            </li>
            <li><a href="#">account</a>
            <!-- First Tier Drop Down -->
                <ul>
                    <li><a href="#">profile</a></li>
                    <li><a href="#">setings</a></li>
                    <li><a href="reset.phtml">password reset</a></li>
                </ul>        
            </li>
            <li><a href="home.html">my studio</a>  
            </li>
            <li><a href="#">Inspiration</a></li>
            <li><a href="#">Contact</a></li>
            <li><a href="#">LOGOUT</a></li>
        </ul>
    </nav>
</div>
    <article>
        <div class="image">
            <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/4273/jeremiah-wilson-1.jpg" alt>
        </div>
        <div class="image">
            <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/4273/jeremiah-wilson-2.jpg" alt>
        </div>
        <div class="image">
            <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/4273/jeremiah-wilson-3.jpg" alt>
        </div>
        <div class="image">
            <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/4273/jeremiah-wilson-4.jpg" alt>
        </div>
        <div class="image">
            <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/4273/jeremiah-wilson-5.jpg" alt>
        </div>
      <!-- images placed inside block elements to deal with a Firefox rendering bug affecting  scaled flexbox images -->
</article>
</body>
</html>