<?php
/*
 *
 *    File created by Roger Ndaba
 *    Project: camagru
 *    File: public.phtml
 *
 */
    include('connect.php');
    session_start();
    $conn = conOpen();
    $useranme = $_POST['user'];
    $stmt = $conn->prepare("SELECT `pic`, `likes`, `username` FROM `images` ORDER BY `create_date` DESC");
    $stmt->execute();
    
?>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="public.css">
    <link rel="stylesheet" href="buttons.css">
    <link rel="icon" href="./images/camagru.png">
    <title>Camagru Public</title>


</head>
<body>
    <div class="icon_wrapper">
        <div class="icon">
        <a href="index.html"><img src="./images/camagru.png" class="ims"></a>    
            <div class="profile">
                <div class="pro_ico"><img src="./images/profile.png" style="width:100%;height:100%"></div>
                <p class="username"><?php echo $_SESSION['user'] ?></p>
            </div>
        </div>
    </div>
    <?php if (isset($_GET['bye'])) echo "<div id='bye'>".$_GET['bye']."</div>"; unset($_GET['bye']);?>
<div id="container">
    <nav>
        <ul>
            <li><a href="#">home</a>
                <ul>
                    <li><a href="login.phtml">LOGIN</a></li>
                    <li><a href="new_account.phtml">SIGN UP</a></li>
                </ul>
            </li>
            <li><a href="#">account</a>
            <!-- First Tier Drop Down -->
                <ul>
                    <li><a href="#">profile</a></li>
                    <li><a href="#">setings</a></li>
                    <li><a href="forgot_password.phtml">password reset</a></li>
                </ul>        
            </li>
            <li><a href="home.phtml">my studio</a>  
            </li>
            <li><a href="#">Inspiration</a></li>
            <li><a href="#">Contact</a></li>
            <?php if(isset($_SESSION) && $_SESSION['user']) echo "<li id='logout' onclick='remove()'><a style='background-color:white'>LOGOUT</a></li>" ?>
        </ul>
    </nav>
</div>
    <article>
        <?php
        
        while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
            echo    '<div class="image">'.
                    '<img src="data:image/png;base64,'.$row['pic'].'">'.
                    '<div class="overlay">'.
                    '<button id="butt" class="button button-like">'.
                    '<i class="fa fa-heart"></i>'.
                    '<span><span id=count>'.$row['likes'].'</span>&nbsp;Like</span>'.
                    '</button>'.
                    '</div>'.
                    '</div>';
        }
        ?>
</article>
     <script>
         function remove() {
             location.href = 'logout.php';
         }

         document.getElementById('butt').addEventListener('click', function() {
            //  window.alert('sdsdsd');
             document.getElementById('butt').classList.toggle("liked");
         });
        window.addEventListener('mousedown', function() {
            var bye = document.getElementById('bye');
            if(bye){
                bye.parentNode.removeChild(bye);
                var url = window.location.href.replace("?bye=good%20bye", "");
                window.history.pushState(null, null, url);
            }
        });
     </script>
</body>
</html>