<?php
/*
 *
 *    File created by Roger Ndaba
 *    Project: camagru
 *    File: public.phtml
 *
 */

 session_start();
?>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="public.css">
    <link rel="stylesheet" href="buttons.css">
    <title>Camagru Public</title>


</head>
<body>
    <div class="icon_wrapper">
        <div class="icon">
        <a href="index.html"><img src="./images/black_camagru.png" class="ims"></a>    
        </div>
    </div>
    <?php if (isset($_GET['bye'])) echo "<div id='bye'>".$_GET['bye']."</div>"; unset($_GET['bye']);?>
<div id="container">
    <nav>
        <ul>
            <li><a href="#">home</a>
                <ul>
                    <li><a href="login.phtml">LOGIN</a></li>
                    <li><a href="new_account.phtml">SIGN UP</a></li>
                </ul>
            </li>
            <li><a href="#">account</a>
            <!-- First Tier Drop Down -->
                <ul>
                    <li><a href="#">profile</a></li>
                    <li><a href="#">setings</a></li>
                    <li><a href="forgot_password.phtml">password reset</a></li>
                </ul>        
            </li>
            <li><a href="home.phtml">my studio</a>  
            </li>
            <li><a href="#">Inspiration</a></li>
            <li><a href="#">Contact</a></li>
            <?php if(isset($_SESSION) && $_SESSION['user']) echo "<li id='logout' onclick='remove()'><a style='background-color:white'>LOGOUT</a></li>" ?>
        </ul>
    </nav>
</div>
    <article>
        <div class="image">
            <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/4273/jeremiah-wilson-1.jpg" alt>
            <div class="overlay">
                <button id="butt" class="button button-like">
                    <i class="fa fa-heart"></i>
                    <span><span id=count>10</span>&nbsp;Like</span>
                </button>
            </div>
        </div>
        <div class="image">
            <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/4273/jeremiah-wilson-2.jpg" alt>
            <div class="overlay">The content of the overlay will be displayed above the img on :hover over.</div>
        </div>
        <div class="image">
            <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/4273/jeremiah-wilson-3.jpg" alt>
            <div class="overlay">The content of the overlay will be displayed above the img on :hover over.</div>
        </div>
        <div class="image">
            <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/4273/jeremiah-wilson-4.jpg" alt>
            <div class="overlay">The content of the overlay will be displayed above the img on :hover over.</div>
        </div>
        <div class="image">
            <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/4273/jeremiah-wilson-5.jpg" alt>
            <div class="overlay">The content of the overlay will be displayed above the img on :hover over.</div>
        </div>
      <!-- images placed inside block elements to deal with a Firefox rendering bug affecting  scaled flexbox images -->
</article>
     <script>
         function remove() {
             location.href = 'logout.php';
         }

         document.getElementById('butt').addEventListener('click', function() {
            //  window.alert('sdsdsd');
             document.getElementById('butt').classList.toggle("liked");
         });
        window.addEventListener('mousedown', function() {
            var bye = document.getElementById('bye');
            if(bye){
                bye.parentNode.removeChild(bye);
                var url = window.location.href.replace("?bye=good%20bye", "");
                window.history.pushState(null, null, url);
            }
        });
     </script>
</body>
</html>