/*
 *
 *    File created by Roger Ndaba
 *    Project: camagru
 *    File: new_account.phtml
 *
 */
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="./images/camagru.png" type="image/x-icon">
    <link rel="stylesheet" href="new_account.css">
    
    <title>new_account</title>
</head>
<body>
    <div class="info_box">
        <div class="info">
            <span class="error_msg" id="error_msg">
                <?php
                ?>
            </span>
            <div class="check_box">WHAT WOULD YOU LIKE TO UPADTE? <br>
                <label><input class="checkhere" type="checkbox" name="name" value="edit_name"> name</label><br>
                <label><input class="checkhere" type="checkbox" name="surname" value="edit_surname"> surname</label><br>
                <label><input class="checkhere" type="checkbox" name="username" value="edit_login"> username</label><br>
                <label><input class="checkhere" type="checkbox" name="email" value="edit_email"></label> email<br>
            </div><br>
            <form id='new_account' action='update_account.php' method='post' accept-charset='UTF-8'>
                
                <input type='hidden' name='submitted' id='submitted' value='1'/>
                <label for='name' >Name<span>*</span></label><br>
                <input type='text' name='name' id='name'  maxlength="50" disabled='disabled' oninput="check()"/><br>

                <label for='surname' >Surname<span>*</span></label>
                <input type='text' name='surname' id='surname' maxlength="50" disabled='disabled' oninput="check()"/><br>

                <label for='login' >Username<span>*</span></label><br>
                <input type='text' name='login' id='login'  maxlength="50" disabled='disabled' oninput="check()"/><br>

                <label for='email' >Email<span>*</span></label><br>
                <input type='text' name='email' id='email'  maxlength="50" disabled='disabled' oninput="check()"/><br>

                <input type='submit' name='submit' id="submit" value='UPDATE' disabled='disabled'/>
                <script>
                    var count = 0;
                    window.addEventListener("load", function() {
                        var boxes = document . getElementsByClassName('checkhere');

                        for (var i = 0; i < boxes.length; i++) {
                                boxes[i].addEventListener('click', function (e) {
                                    if (this.checked) {
                                        count++;
                                        document.getElementById(this.value.replace('edit_', '')).removeAttribute('disabled');
                                    }
                                    else {
                                        count--;
                                        document.getElementById(this.value.replace('edit_', '')).setAttribute('disabled', 'disabled');
                                    }
                            });
                        }
                    });
                    function check(){
                        var reg = /^[a-zA-Z\-]+$/,
                        regem = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/,
                        usr = document.getElementById('login'),
                        fname = document.getElementById('name'),
                        lname = document.getElementById('surname'),
                        email = document.getElementById('email'),
                        tex = '';
                        if (usr.value !='' && !usr.value.match(reg)) {
                            tex += 'alphabets and numbers please in username filed<br>';
                        }
                        if (fname.value !='' && !fname.value.match(reg)) {
                            tex += 'only numbers and letters on name field.<br>';
                        }
                        if (lname.value !='' && !lname.value.match(reg)) {
                            tex += 'alphabets and numbers please in lastname filed<br>';
                        }
                        if (email.value !='' && !regem.test(email.value)) {
                            tex += 'email should have formart login@domain.ext<br>';
                        }
                        document.getElementById('error_msg').innerHTML = tex;
                    }
                </script>
            </form>
        </div>
    </div>
</body>
</html>